default: &default
  adapter: postgresql
  encoding: unicode
  username: pavel
  password: 123
  pool: 80

development:
  <<: *default
  database: test-api_development

test:
  <<: *default
  database: test-api_test

production:
  <<: *default
  database: test-api_development
